apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-namespace
spec:
  selector:
    matchLabels:
      app: prod-namespace
  replicas: 2
  template:
    metadata:
      labels:
        app: prod-namespace
    spec:
      containers:
        - name: prod-namespace
          image: doandnguyen/node-prod:5
          ports:
            - containerPort: 3000
